### ISSUE TITLE
[catr] tests unreliable?

### ISSUE THREAD

**Issue by florianhumblot** [kyclark/command-line-rust#11]
Hey there,
I'm following along the examples in the book and I can't seem to get the tests for catr to pass...
![image](https://user-images.githubusercontent.com/31630192/229344206-5779a3fa-681d-4af2-8cfc-7531f8e5d4b3.png)

When I use the debugger to get some idea it seems that the test doesn't read the expected outputs correctly:
![image](https://user-images.githubusercontent.com/31630192/229344367-662112ad-2236-4f86-bd8b-4922d6307c2c.png)

But if I do a hex-dump of the file contents it seems to be just fine? 
![image](https://user-images.githubusercontent.com/31630192/229344476-fe33c941-96a8-40e8-b8d0-ea169ef9ee4b.png)
I tried re-generating the outputs with the script in this repository but that doens't seem to help.
Anyone have an idea? 

The code is from the tests itself, unmodified:
```rust
fn run(args: &[&str], expected_file: &str) -> TestResult {
    let expected = fs::read_to_string(expected_file)?;
    Command::cargo_bin(PRG)?
        .args(args)
        .assert()
        .success()
        .stdout(expected);
    Ok(())
}
```

**Comment by richo225** [comment]
Hey @florianhumblot , I had exactly the same issue and the test output is super confusing. What fixed it for me was adding final line breaks to all the input files in my editor and regenerating the expected directory:

![Screenshot 2023-05-15 at 02 01 12](https://github.com/kyclark/command-line-rust/assets/18379191/d6e20002-ff22-4c21-b46e-a850291d671e)
![Screenshot 2023-05-15 at 02 01 00](https://github.com/kyclark/command-line-rust/assets/18379191/5320da61-9088-4727-a192-a3ee463eabc1)

**Comment by richo225** [comment]
You're welcome to copy my expected directory and try it out https://github.com/richo225/command-line-rust/tree/d586c7afbd4654e52b065da6e3185fe54a4274b2/catr/tests/expected

**Comment by florianhumblot** [comment]
@richo225 thanks for the hint! I already added line breaks to the end of file, but changing the line endings to LF rather than CRLF seems to have fixed it. Kind of a weird issue to have lol
