### ISSUE TITLE
Chapter 3: tests failed because of the new line

### ISSUE THREAD

**Issue by jason89521** [kyclark/command-line-rust#16]
It seems that the `cat` wouldn't add the new line at the last position. However, the solution of this repo used `println!` to print the result. It causes the test failed.

After I change the code to the following, the tests pass

```rs
pub fn run(config: Config) -> MyResult<()> {
    for filename in &config.files {
        match open(&filename) {
            Err(err) => eprintln!("{}: {}", filename, err),
            Ok(buf) => {
                let mut line_num = 0usize;
                let mut lines: Vec<String> = vec![];
                for line_result in buf.lines() {
                    let line = line_result?;
                    line_num += 1;
                    if config.number_lines {
                        lines.push(format!("{:>6}\t{}", line_num, line));
                    } else if config.number_nonblank_lines {
                        if line.is_empty() {
                            line_num -= 1;
                            lines.push("".into());
                        } else {
                            lines.push(format!("{:>6}\t{}", line_num, line))
                        }
                    } else {
                        lines.push(format!("{}", line))
                    }
                }

                let result = lines.join("\n");
                print!("{}", result)
            }
        }
    }
    Ok(())
}
```

**Comment by kyclark** [comment]
Which test fails? All 20 pass for me with the provided solution. 

Although I appreciate that you found an alternate solution, I would caution that using a vector to hold all the lines of input will crash your program if you have an input file that exceeds the available memory on your machine.

**Comment by jason89521** [comment]
<img width="1512" alt="image" src="https://github.com/kyclark/command-line-rust/assets/47748132/2757cccf-7d7e-4b96-8d20-ee58c8d09d2e">

Almost all tests failed. 😨

**Comment by kyclark** [comment]
Would you mind please providing me your source code, preferably a GitHub repo so I can pull and test myself?

**Comment by jason89521** [comment]
Sure! The repo's [link](https://github.com/jason89521/cli-rust-book).

**Comment by kyclark** [comment]
When I clone your repo and run "cargo test" in the "catr" directory, all tests pass. Can you ensure the failing code is pushed?

**Comment by jason89521** [comment]
Sorry.

I have push the failing code, please checkout to the `catr/fail` branch.

**Comment by kyclark** [comment]
The test failures are because files in your "tests/expected" directory are different from those in my repo. It's fine if you want your tool to produce different output from what mine expects, but you should update your "expected" files to match the actual output from your code. In my case, I was trying to duplicate the behavior of the original tools and generated those files using the "mk-outs.sh" on macOS, which means I was getting the output from the BSD version of "cat" as described in the text.

**Comment by jason89521** [comment]
But the test files were generated by 'mk-outs.sh', and I am also using macOS. Why do we have different outputs?

**Comment by kyclark** [comment]
I'm not sure, but the expected values for the tests are read from these files. I think these were only different in the branch, but I didn't check that. Anyway, I think this means your version was fine.

**Comment by jason89521** [comment]
Okay, thank you! I will find a solution to avoid storing the string in the vector. Thanks for your advice!
