### ISSUE TITLE
Examples compilation  note for  RL8

### ISSUE THREAD

**Issue by tjyang** [kyclark/command-line-rust#6]
Hi

I had to replace "2021" with 2018 in older rust environment come with Linux distro.
This change will run  "./test.sh" successfully using RL8(RockyLinux 8.5)'s default rust rpm pkgs.

```
 find . -type f -name "Cargo.toml" -exec perl -pi -e 's!2021!2018!'  {} \;
```

**Comment by kyclark** [comment]
Thanks for leaving this comment. I'm sure it will be helpful to people using this distro. I will close as you propose a workaround.
