### ISSUE TITLE
Chapter 3: catr implementation deviates from cat implementation for line numbers with multiple files

### ISSUE THREAD

**Issue by SimonCW** [kyclark/command-line-rust#9]
Hi @kyclark, the version of catr developed in chapter 03 starts the line numbers from `1` for each new file, i.e.
```
cargo run -q -- -n tests/inputs/fox.txt tests/inputs/spiders.txt
```
produces:
```
     1  The quick brown fox jumps over the lazy dog.
     1  Don't worry, spiders,
     2  I keep house
     3  casually.
```
whereas 
``` 
cat -n tests/inputs/fox.txt tests/inputs/spiders.txt
```
produces 
```
     1  The quick brown fox jumps over the lazy dog.
     2  Don't worry, spiders,
     3  I keep house
     4  casually.
```

The tests aren't failing b/c the `tests/expected/all.*.out` files are incorrect. This can be seen by re-running `bash mk-outs.sh && cargo test`.

I created a PR to fix this here: https://github.com/kyclark/command-line-rust/pull/10

Off-Topic:
Learning Rust with the book is a lot of fun! Thank you!

**Comment by kyclark** [comment]
Simon,

Thanks for the report. I guess you and I have different versions of "cat" installed. On my macOS, I see the following:

$ cargo run -q -- -n tests/inputs/fox.txt tests/inputs/spiders.txt
     1	The quick brown fox jumps over the lazy dog.
     1	Don't worry, spiders,
     2	I keep house
     3	casually.
$ cat -n tests/inputs/fox.txt tests/inputs/spiders.txt
     1	The quick brown fox jumps over the lazy dog.
     1	Don't worry, spiders,
     2	I keep house
     3	casually.

It's fine if you prefer to implement the version on your computer--just be sure to update the tests to reflect what you expect.

Glad you dig the book. Please consider leaving a positive review on Amazon.

**Comment by SimonCW** [comment]
Ahh, that makes sense, I haven't thought of that.

**Comment by NilVentosa** [comment]
I have the same issue as Simon on my new macbook air's GNU cat. Maybe Apple changes the version they ship...

**Comment by kyclark** [comment]
That's good to know. Thanks for leaving the comment in case others see the same.
